name: Approve PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Approve PR
        uses: actions/github-script@v6
        with:
          script: |
            github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
